apiVersion: apps/v1 
kind: Deployment
metadata:
  name: flink-deployment-master-task-manager
  labels:
    app: flink-app-master
spec:
  selector:
    matchLabels:
      app: flink-app-master
      tier: flink-deployment-master
  replicas: 1
  template:
    metadata:
      labels:
        app: flink-app-master
        tier: flink-deployment-master
    spec:
      containers:
      - name: flink-image
        image: sameerbhat/flink-fresh
        command: ["/opt/flink/bin/taskmanager.sh", "start-foreground"]
        ports:
        - containerPort: 8081
          name: dashboard
        - containerPort: 6123
          name: process
        - containerPort: 6124
          name: blob
        - containerPort: 6122
          name: rpc
        volumeMounts:
          - mountPath: /tmp
            name: tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      volumes:
        - emptyDir: {}
          name: tmp