apiVersion: v1
kind: Service
metadata:
  name: flink-deployment-master
  labels:
    app: flink-app-master
    tier: flink-deployment-master
spec:
  type: NodePort
  ports:
  - port: 8081
  selector:
    app: flink-app-master
    tier: flink-deployment-master