apiVersion: v1
kind: Service
metadata:
  name: flink-deployment-master
  labels:
    app: flink-app-master
    tier: flink-deployment-master
spec:
  type: NodePort
  ports:
  - name: dashboard
    port: 8081
  # targetPort: 8081
  - name: process
    port: 6123
  # targetPort: 6123
  selector:
    app: flink-app-master
    tier: flink-deployment-master